name = "blog"
type = "webpack"
workers_dev = true

# https://developers.cloudflare.com/workers/platform/environments#environment-variables
# [secrets]
# LOGDNA_INGESTION_KEY

[env.production]
workers_dev = false
routes = ["blog.kowalczyk.info/*", "kowalczyk.info/*"]
zone_id = "80741a2b8f1a5726bf84ac76d73ff8f9"

[site]
bucket = "./www_generated"
entry-point = "workers-site"
