name: Deploy to netlify
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build as a sanity check
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: go run . -ci-build
