name: Deploy to netlify
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Test
        run: go test -v .

      - name: Install @cloudflare/wrangler
        run: yarn install

      - name: Regenerate HTML and deploy to Cloudflare
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: go run . -deploy-prod
