name: Update from notion
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 4 * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Check out source code
        uses: actions/checkout@v1

      - name: build the program
        run: go build -o blog

      - name: Update from notion and deploy if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: go run -ci-daily
